### ISSUE TITLE
Does not capture photos on 2024 M4 iPad Pro lineup

### ISSUE THREAD

**Issue by mysnoopy** [OmChachad/Pencilera#1]
After tapping the Apple Pencil Pro, the screen of the iPad Pro m4 2024 flashed, and a photo was taken. However, I couldn't find the new photo in the Photos app. I attempted this more than 20 times and encountered the same result each time. I have already granted full photo access to the app.

**Comment by OmChachad** [comment]
Hi!

Yes, this is a known issue. I'm currently working on finding a solution to why this happens. The code for the camera is from an Apple Sample Project, and even the sample project fails on the new iPad Pros. Currently trying to find the root of issue before I can work towards fixing it.

**Comment by OmChachad** [comment]
Hi, I just resolved this issue in the latest commit.

You can help test it via this link: https://testflight.apple.com/join/M5juquCP

The build should be rolled out to the App Store soon after a few rounds of testing.

**Comment by mysnoopy** [comment]
I tested it several times with different settings, and it all works. Thank you for fixing the bugs.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
